[default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = '0.8.10'
auto_detect_solc = false
optimizer = true
optimizer_runs = 20_000
fuzz_runs = 1_000

# See more config options https://github.com/gakonst/foundry/tree/master/config